name: CI/CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch: # Allows manual triggering from the GitHub Actions UI

env:
  PROJECT_ID: ${{ secrets.PROJECT_ID }}
  BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
  GOOGLE_SERVICE_ACCOUNT_KEY: ${{ secrets.GOOGLE_SERVICE_ACCOUNT_KEY}}
  SERVICE_NAME: offerforyou
  REGION: europe-central2

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.24.4'
        check-latest: true

    - name: Build Go app
      working-directory: ./cmd
      run: go build -v ./...

    - name: Run Go tests
      run: go test ./... -v
      
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Authenticate with Google Cloud
      - name: Authenticate with Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ env.GOOGLE_SERVICE_ACCOUNT_KEY }}

      # Install Google Cloud SDK
      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ env.PROJECT_ID }}

      # Deploy to Cloud Run
      - name: Deploy server to Cloud Run
        run: |
          gcloud run deploy ${{ env.SERVICE_NAME }} \
            --source . \
            --platform managed \
            --region ${{ env.REGION }} \
            --allow-unauthenticated \
            --set-env-vars "BOT_TOKEN=${{ env.BOT_TOKEN }}"